name: Conference Abstracts
favicon: null
layout_spectrum: 0.5386422702576965
typography_spectrum: 0.8088280812371522
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.22023118194192648
  lightness: 0.9712734853383154
  saturation: 0.017216287087649107
  rhythmicContrast: 0.5980252209119499
purpose: []
